---
# tasks file for worker-setup
- name: Check if bash join exist
  stat:
    path: /tmp/join-kube-clust.sh
  register: __sh_join

- name: Copy join command to worker nodes.
  copy:
    src: /tmp/join-kube-clust.sh
    dest: /tmp/join-kube-clust.sh
    mode: 0777
  when: not __sh_join.stat.exists


- name: Join the Worker nodes with the master.
  command: bash /tmp/join-kube-clust.sh
  register: joined_or_not
- debug:
    msg: "{{ joined_or_not.stdout }}"