## ansible-galaxy collection install kubernetes.core
- name: Check if kubeconfig already exists
  stat:
    path: "{{ ansible_env.HOME }}/.kube"
  register: __kubeconfig_already_init

- name: Create .kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    owner: root
    group: root
  when: not __kubeconfig_already_init.stat.exists

- name: Copy admin.conf to .kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    remote_src: true
  when: not __kubeconfig_already_init.stat.exists
  
- name: prerequisites
  apt:
    name: python3-yaml
    state: present

- name: Install helm if not exists
  unarchive:
    src: "https://get.helm.sh/helm-v{{ addons_helm_version }}-linux-amd64.tar.gz"
    dest: /usr/local/bin
    extra_opts: "--strip-components=1"
    owner: root
    group: root
    mode: 0755
    remote_src: true
  args:
    creates: /usr/local/bin/helm
