#generer par terraform
all:
  children:
    kubernetes:
      children:
        haproxy:
          hosts:
            VM-WBO-haproxy:
              ansible_host: 4.233.87.1
        master:
          hosts:
            VM-WBO-Clust-kubernete-Node-manager1:
              ansible_host: 4.233.87.142
        workers:
          hosts:
            VM-WBO-Clust-kubernete-Node2:
              ansible_host: 4.233.87.197
            VM-WBO-Clust-kubernete-Node3:
              ansible_host: 4.233.82.93
            VM-WBO-Clust-kubernete-Node4:
              ansible_host: 4.233.87.77
            VM-WBO-Clust-kubernete-Node5:   
              ansible_host: 4.233.87.173

