#generer par terraform
all:
  children:
    kubernetes:
      children:
        haproxy:
          hosts:
            VM-WBO-haproxy:
              ansible_host: 52.143.177.156
        master:
          hosts:
            VM-WBO-Clust-kubernete-Node-manager1:
              ansible_host: 52.143.183.104
        workers:
          hosts:
            VM-WBO-Clust-kubernete-Node2:
              ansible_host: 52.143.183.21
            VM-WBO-Clust-kubernete-Node3:
              ansible_host: 52.143.177.76
            VM-WBO-Clust-kubernete-Node4:
              ansible_host: 52.143.183.249
            VM-WBO-Clust-kubernete-Node5:   
              ansible_host: 52.143.177.32

