---
# defaults file for install-kube

https_packages:
- name: apt-transport-https
- name: ca-certificates
- name: software-properties-common
- name: gnupg


python_pip:
  - python3
  - python3-jsonpatch
  - pipx

pipx_packages:
  - jsonpatch
  - PyYAML
  - kubernetes 


docker_packages:
- name: containerd.io



k8s_packages:
- name: kubeadm 
- name: kubelet 
- name: kubectl


node_ip_master1: 10.0.1.10
POD_NETWORK: 10.0.244.0/16